src/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^videos/', include('mrupload.urls')),

    # 3rd party apps
    url(r'^upload/', include('django_file_form.urls')),
]

src/mrupload/urls.py
from django.conf.urls import url

from .views import UploadView, LibraryView, VideoUpdateView

urlpatterns = [
    url(regex=r'^$',
        view=LibraryView.as_view(),
        name='library'),
    url(regex=r'^upload/$',
        view=UploadView.as_view(),
        name='upload_videos'),
    url(regex=r'^update/(?P<pk>[0-9]+)/$',
        view=VideoUpdateView.as_view(),
        name='update_video'),
]

src/mrupload/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import smart_text

import boto

from .validators import validate_file_type, validate_file_size

User =  settings.AUTH_USER_MODEL


def mr_upload_location(instance, filename):
    return "{user}/videos/{file}".format(
            user=instance.user.username,
            file=filename
            )


class Video(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=120)
    file = models.FileField(
        upload_to=mr_upload_location,
        validators=[validate_file_type, validate_file_size],
        max_length=200,
    )
    description = models.TextField()


    def __unicode__(self):
        return smart_text(self.title)

    def get_file_secure_url(self):
        """
        Returns a secure URL for the `file` that was uploaded to S3

        # TODO: needs tests
        """
        conn = boto.s3.connect_to_region(
            settings.S3DIRECT_REGION,
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            is_secure=True
        )
        bucket = conn.get_bucket(settings.AWS_STORAGE_BUCKET_NAME)
        key = bucket.get_key(self.file.name)

        if key:
            return key.generate_url(expires_in=settings.AWS_FILE_EXPIRE, method='GET')


@receiver(post_save, sender=Video, dispatch_uid='new_video')
def new_video_created(sender, instance, created, **kwargs):
    if created:
        print 'URL of new Video is: %s' % instance.file.url

src/mrupload/forms.py
from django import forms

from django_file_form.forms import FileFormMixin, MultipleUploadedFileField

from .models import Video


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = [
            'title',
            'file',
            'description',
        ]

    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['file'] = forms.FileField(widget=forms.FileInput)

        if self.instance.pk:
            current_file_link = 'Currently: <a href="{file_url}">{file_name}</a>'
            self.fields['file'].help_text = current_file_link.format(
                file_url=self.instance.get_file_secure_url(),
                file_name=self.instance.file.name,
            )


class MultipleFileForm(FileFormMixin, forms.Form):
    video_files = MultipleUploadedFileField(label='Drop files to upload.')

src/mrupload/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import FormView, ListView, UpdateView

from .models import Video
from .forms import MultipleFileForm, VideoForm


class LibraryView(LoginRequiredMixin, ListView):
    model = Video
    template_name = 'mrupload/library.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class UploadView(LoginRequiredMixin, FormView):
    form_class = MultipleFileForm
    template_name = 'mrupload/upload.html'
    success_url = reverse_lazy('library')

    def get_context_data(self, **kwargs):
        context = super(UploadView, self).get_context_data(**kwargs)
        context['MAX_VIDEO_FILE_SIZE'] = settings.MAX_VIDEO_FILE_SIZE
        context['VALID_FILE_MIME_TYPES'] = settings.VALID_FILE_MIME_TYPES

        return context

    def form_valid(self, form):
        for video in form.cleaned_data['video_files']:
            Video.objects.create(
                user=self.request.user,
                title=video.name,
                file=video,
            )
        form.delete_temporary_files()
        return HttpResponseRedirect(self.get_success_url())


class VideoUpdateView(LoginRequiredMixin, UpdateView):
    model = Video
    template_name = 'mrupload/update_video.html'
    success_url = reverse_lazy('library')
    form_class = VideoForm

    def get_object(self):
        return get_object_or_404(
            self.model,
            user=self.request.user,
            pk=self.kwargs.get('pk'),
        )

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mr Upload Base Template</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <style>
    {% block styles %}

    {% endblock %}
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>

      {% block content %}
      {% endblock %}
    </div>







    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- jQuery Color for Background Animation -->
    <script src="https://code.jquery.com/color/jquery.color-2.1.2.min.js"></script>
    <script src="{% static "ajaxuploader/js/fileuploader.js" %}"></script>
    <script src="{% static "file_form/file_form.js" %}"></script>
    <link rel="stylesheet" href="{% static "ajaxuploader/css/fileuploader.css" %}">
    <script>
    $(document).ready(function(){
        {% block jquery %}
        {% endblock %}
    })
    </script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


  </body>
</html>

src/templates/mrupload/formset_upload_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<script>

{% block jquery %}

function updateEmptyFormIDs(element, totalForms){
    var thisInput = element

    // get current form input name
    var currentName = element.attr('name')
    // replace "prefix" with actual number
    var newName = currentName.replace(/__prefix__/g, totalForms)
    // console.log(newName)
    
    // update input with new name
    thisInput.attr('name', newName)
    thisInput.attr('id', "id_" + newName)


    // create a new form row id
    var newFormRow = element.closest(".form-row");
    var newRowId =  "row_id_" + newName
    newFormRow.attr("id", newRowId)

    // add new class for basic graphic animation
    newFormRow.addClass("new-parent-row")
    // update form group id
    var parentDiv = element.parent();
    parentDiv.attr("id", "parent_id_" + newName)

    // update label id
    var inputLabel = parentDiv.find("label")
    inputLabel.attr("for", "id_" + newName)
    

    // return created row
    return newFormRow
}



$('.add-new-form').click(function(e) {
    e.preventDefault()
    // form id like #id_form-TOTAL_FORMS
    var formId = "id_form-TOTAL_FORMS"

    // copy empty form
    var emptyRow = $("#empty-row").clone();
    // remove id from new form
    emptyRow.attr("id", null)
    // Insert row after last row
    
    // get starting form count for formset
    var totalForms = parseInt($('#' + formId).val());
    
    // create new form row from empty form row
    var newFormRow;
    emptyRow.find("input, select, textarea").each(function(){
        newFormRow = updateEmptyFormIDs($(this), totalForms)
    })


    // insert new form at the end of the last form row
    $(".form-row:last").after(newFormRow)

    // update total form count (to include new row)
    $('#'+ formId).val(totalForms + 1);

    // scroll page to new row
    $('html, body').animate({
        scrollTop: newFormRow.offset().top - 100
    }, 500, function(){
        // animate background color
        // requires: jQuery Color: https://code.jquery.com/color/jquery.color-2.1.2.min.js
        newFormRow.animate({
            backgroundColor: "#fff"
        }, 1500)
    });

});



{% endblock %}

</script>




<style>
{% block styles %}

#empty-row {
    display: none
}
.form-row {
    border-bottom: 1px solid #333;
    margin: 20px 0px;
    padding: 20px 10px;
}

.new-parent-row {
    background-color: rgb(75, 186, 228);
}
    
</style>
{% endblock %}


{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Formset View</h1>
    <form action='' method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        <div class='btn-group'>
            <input class='btn btn-primary' type='submit' value='Save' /> 
            <a class='btn btn-default' href='{{ request.build_absolute_uri }}'>Cancel</a>
            <a class='btn btn-link add-new-form' href='#'>+ Add new form</a>
        </div>
        <br/>
        {{ formset.management_form }}
        {% for form in formset %}
        <div class='form-row'>
            {{ form|crispy }}
        </div>
        {% endfor %}

        <div class='form-row' id='empty-row'>
            {{ formset.empty_form.as_p }}
        </div>

        <div class='btn-group'>
            <input class='btn btn-primary' type='submit' value='Save' /> 
            <a class='btn btn-default' href='{{ request.build_absolute_uri }}'>Cancel</a>
            <a class='btn btn-link add-new-form' href='#'>+ Add new form</a>
        </div>
    </form>
</div>
<br/>
<br/>


{% endblock %}

src/templates/mrupload/library.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Your Library</h1>
        <ul>
            {% for video in video_list %}
                <li>
                    <a href="{% url 'update_video' video.pk %}">{{ video.title }}</a>
                </li>
            {% empty %}
                No videos uploaded.
            {% endfor %}
        </ul>
    </div>
{% endblock %}

src/templates/mrupload/update_video.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Update Video</h1>
        <form id="update-video-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="btn-group">
                <input class='btn btn-primary' type='submit' value='Save' />
            </div>
        </form>
    </div>
{% endblock %}

src/templates/mrupload/upload.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

<script>
{% block jquery %}
    $(function(){
        initUploadFields(
            $('#multiple-file-form'),
            {
                validation: {
                    acceptFiles: {{ VALID_FILE_MIME_TYPES|safe }},
                    sizeLimit: {{ MAX_VIDEO_FILE_SIZE }}
                }
            });
    });
{% endblock %}
</script>

{% block content %}
    {% include 'django_file_form/upload_template.html' %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Upload Videos</h1>
        <form id="multiple-file-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                {{ form|crispy }}
            </div>
            <div class="btn-group">
                <input class='btn btn-primary' type='submit' value='Save' />
            </div>
        </form>
    </div>
{% endblock %}